"""test task id

Revision ID: 4c731534bbcf
Revises: d92e5040ccef
Create Date: 2020-06-25 08:43:26.031405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c731534bbcf'
down_revision = 'd92e5040ccef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engine', sa.Column('test_task_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('engine', 'test_task_id')
    # ### end Alembic commands ###
