"""Add demo column

Revision ID: a46b49b730d4
Revises: cd5be9742024
Create Date: 2021-11-10 15:30:25.370380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a46b49b730d4'
down_revision = 'cd5be9742024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('demo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'demo')
    # ### end Alembic commands ###
