"""langs

Revision ID: cd5be9742024
Revises: c0c7a3a22cd8
Create Date: 2021-05-10 13:12:05.357088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from app import db
from app.models import Corpus, Language, User, UserLanguage, Engine, File

revision = 'cd5be9742024'
down_revision = 'c0c7a3a22cd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_language',
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'user_id')
    )

    for user in User.query.all():
        for lang in Language.query.all():
            user_lang = UserLanguage(code=lang.code, name=lang.name, user_id=user.id)
            db.session.add(user_lang)
    db.session.commit()

    op.add_column('corpus', sa.Column('user_source_id', sa.Integer(), nullable=True))
    op.add_column('corpus', sa.Column('user_target_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('corpus') as batch_op:
        batch_op.create_foreign_key('fk_corpus_user_target_id', 'user_language', ['user_target_id'], ['id'])
        batch_op.create_foreign_key('fk_corpus_user_source_id', 'user_language', ['user_source_id'], ['id'])

    for corpus in Corpus.query.all():
        source_lang = UserLanguage.query.filter_by(code=corpus.source_id, user_id=corpus.owner_id).one()
        corpus.user_source_id = source_lang.id

        target_lang = UserLanguage.query.filter_by(code=corpus.target_id, user_id=corpus.owner_id).one()
        corpus.user_target_id = target_lang.id
    db.session.commit()

    op.add_column('engine', sa.Column('user_source_id', sa.Integer(), nullable=True))
    op.add_column('engine', sa.Column('user_target_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('engine') as batch_op:
        batch_op.create_foreign_key('fk_engine_user_source_id', 'user_language', ['user_source_id'], ['id'])
        batch_op.create_foreign_key('fk_engine_user_target_id', 'user_language', ['user_target_id'], ['id'])

    for engine in Engine.query.all():
        if engine.source_id and engine.target_id:
            if engine.uploader_id:
                source_lang = UserLanguage.query.filter_by(code=engine.source_id, user_id=engine.uploader_id).one()
                target_lang = UserLanguage.query.filter_by(code=engine.target_id, user_id=engine.uploader_id).one()
            else:
                source_lang = UserLanguage.query.filter_by(code=engine.source_id).first()
                target_lang = UserLanguage.query.filter_by(code=engine.target_id).first()

            engine.user_source_id = source_lang.id
            engine.user_target_id = target_lang.id
            db.session.commit()

    op.add_column('file', sa.Column('user_language_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('file') as batch_op:
        batch_op.create_foreign_key('fk_file_user_language_id', 'user_language', ['user_language_id'], ['id'])

    for file in [f for f in File.query.all() if f.language_id]:
        if file.uploader_id:
            lang = UserLanguage.query.filter_by(code=file.language_id, user_id=file.uploader_id).one()
        else:
            lang = UserLanguage.query.filter_by(code=file.language_id).first()

        file.user_language_id = lang.id
    db.session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corpus') as batch_op:
        batch_op.drop_column('user_source_id')
        batch_op.drop_column('user_target_id')

    with op.batch_alter_table('engine') as batch_op:
        batch_op.drop_column('user_source_id')
        batch_op.drop_column('user_target_id')

    with op.batch_alter_table('file') as batch_op:
        batch_op.drop_column('user_language_id')

    op.drop_table('user_language')
    # ### end Alembic commands ###
