"""runtime

Revision ID: d92e5040ccef
Revises: 756557b577a6
Create Date: 2020-06-12 12:09:11.791723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd92e5040ccef'
down_revision = '756557b577a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engine', sa.Column('runtime', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('engine', 'runtime')
    # ### end Alembic commands ###
