"""Add test score

Revision ID: dd1bcfc4cb0a
Revises: ee1a8f76afb4
Create Date: 2020-07-22 08:24:01.753667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd1bcfc4cb0a'
down_revision = 'ee1a8f76afb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engine', sa.Column('test_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('engine', 'test_score')
    # ### end Alembic commands ###
