version: '3.1'

services:
    mutnmt:
        container_name: mutnmt
        image: mutnmt:latest
        ports:
            - 5000:5000
        environment: 
            - DEBUG=0
        volumes:
            - ./data:/opt/mutnmt/data
            - ./app/preloaded:/opt/mutnmt/app/preloaded
        deploy:
            resources:
                reservations:
                    devices:
                        -
                            driver: nvidia
                            count: all
                            capabilities: [gpu, utility]
