language: python
python:
  - "3.6"
before_install:
  # Install CPU version of PyTorch.
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install https://download.pytorch.org/whl/cpu/torch-1.1.0-cp36-cp36m-linux_x86_64.whl; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install https://download.pytorch.org/whl/cpu/torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl; fi
  # Install remaining dependencies
  - pip install -r requirements.txt
install:
  - python setup.py install
script:
  - pytest
  - pylint --rcfile=.pylintrc joeynmt
